[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd frontend && npm ci"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd frontend && npm run preview -- --host 0.0.0.0 --port $PORT"
